import type { PillarEditorial } from '../types';

// Batch-converted editorial. Claim-audited; publish bar decides.
export const inrPricingBilling: PillarEditorial = {
  "pillarId": "inr-pricing-billing",
  "updated": "2026-09-06",
  "definition": "Transparent INR pricing structure with native UPI, NetBanking, automated GST-compliant invoicing, and zero international markup for Indian developers and organizations.",
  "sections": [
    {
      "heading": "Transparent INR Pricing Structure",
      "paragraphs": [
        "CodingAgent's pricing is designed specifically for the Indian market, with all costs denominated in Indian Rupees and no hidden international markups. The pricing structure is simple and predictable: per-token costs for model inference, per-seat costs for user access, and optional enterprise features for larger organizations.",
        "Per-token pricing is transparent and published openly. Developers can see exactly how much each token costs for each model, enabling accurate cost estimation for projects. The pricing includes both input tokens (code sent to the model) and output tokens (code generated by the model), with different rates for different model tiers. Local models (running on your own hardware) have no per-token cost, only the infrastructure cost of running them.",
        "Per-seat pricing provides unlimited usage for individual developers within their allocated token budget. This removes the friction of per-request billing and enables developers to use agents freely without worrying about costs for each interaction. Enterprise plans offer volume discounts and custom token budgets based on organizational needs.",
        "All pricing is GST-compliant, with taxes calculated automatically and included in invoices. This eliminates the complexity of tax calculation for organizations and ensures compliance with Indian tax regulations."
      ]
    },
    {
      "heading": "UPI and NetBanking Integration",
      "paragraphs": [
        "Payment processing is integrated with India's most popular payment methods: UPI (Unified Payments Interface) and NetBanking. UPI enables instant, free payments using mobile apps like Google Pay, PhonePe, and Paytm. NetBanking enables direct bank transfers for larger organizational payments.",
        "The UPI integration supports both one-time payments and recurring subscriptions. For subscriptions, the system uses UPI AutoPay, which enables automatic recurring payments with user consent. This eliminates the need for manual payment each month while maintaining user control through the UPI app interface.",
        "NetBanking integration supports all major Indian banks and enables direct debit from bank accounts. This is particularly useful for enterprise customers who prefer to pay through their corporate banking systems. The integration handles payment verification automatically, confirming successful payments and activating services immediately.",
        "Both payment methods are PCI-DSS compliant and follow RBI guidelines for payment processing. Payment data is encrypted in transit and at rest, and the system never stores sensitive payment information like CVV or full account numbers."
      ]
    },
    {
      "heading": "Automated GST-Compliant Invoicing",
      "paragraphs": [
        "Every payment automatically generates a GST-compliant invoice that meets all requirements of the Indian GST regime. Invoices include: GSTIN (Goods and Services Tax Identification Number), place of supply, tax breakdown (CGST, SGST, IGST as applicable), HSN code (Harmonized System of Nomenclature), and all other required fields.",
        "The invoicing system automatically determines the correct tax treatment based on the customer's location and GSTIN. For intra-state supplies, it applies CGST and SGST. For inter-state supplies, it applies IGST. For exports (customers outside India), it applies zero-rated treatment with appropriate documentation.",
        "Invoices are generated in PDF format and are available for download from the billing dashboard. They can also be automatically emailed to designated recipients. For organizations that need invoices in specific formats or with additional fields, custom invoice templates are available.",
        "The system maintains a complete audit trail of all invoices, payments, and tax calculations. This audit trail is immutable and can be exported for compliance audits. It provides confidence that all tax obligations are being met correctly."
      ]
    },
    {
      "heading": "Zero International Markup",
      "paragraphs": [
        "Unlike many global SaaS products that add international markups for Indian customers, CodingAgent's pricing is designed specifically for the Indian market with no hidden costs. The INR prices published are the actual prices paid, with no currency conversion fees, no international transaction charges, and no hidden surcharges.",
        "This transparency extends to all aspects of billing. There are no setup fees, no hidden maintenance charges, and no surprise price increases. Price changes are communicated well in advance, and existing customers are grandfathered at their current rates for the duration of their subscription period.",
        "For organizations that need to compare costs across different usage patterns, the pricing calculator provides accurate estimates based on actual usage data. The calculator accounts for all factors: number of users, expected token consumption, model selection, and enterprise features. This enables accurate budgeting without surprises.",
        "The zero-markup approach reflects CodingAgent's commitment to the Indian developer community. By pricing specifically for the Indian market, the platform ensures that powerful AI coding assistance is accessible to Indian developers and organizations without the cost barriers that often exist with international products."
      ]
    },
    {
      "heading": "Enterprise Billing and Cost Management",
      "paragraphs": [
        "For enterprise customers, CodingAgent provides comprehensive billing and cost management features that enable organizations to control costs, allocate expenses, and optimize usage. These features are designed for the complexity of enterprise environments where multiple teams, projects, and cost centers need to be managed.",
        "Cost allocation enables organizations to assign costs to specific teams, projects, or cost centers. This enables accurate chargeback or showback, ensuring that teams are accountable for their usage and can optimize accordingly. Cost allocation is flexible, supporting hierarchical structures where costs can be rolled up from projects to teams to departments.",
        "Budget management enables organizations to set token budgets for teams or projects and receive alerts when budgets are approaching limits. This prevents unexpected cost overruns and enables proactive cost management. Budgets can be set monthly, quarterly, or annually, and can be adjusted as needed.",
        "Usage analytics provide detailed visibility into token consumption, model usage, and cost trends. Organizations can identify which teams are using the most resources, which models are most cost-effective, and where optimization opportunities exist. This data-driven approach enables continuous cost optimization."
      ]
    },
    {
      "heading": "Payment Security and Compliance",
      "paragraphs": [
        "All payment processing follows the highest security standards and complies with Indian regulations. The payment system is PCI-DSS Level 1 certified, the highest level of payment security certification. This ensures that all payment data is handled with the utmost security.",
        "The system complies with RBI (Reserve Bank of India) guidelines for payment processing, including data localization requirements. Payment data is stored in India and processed through Indian payment gateways. This ensures compliance with data sovereignty requirements and reduces latency for payment processing.",
        "For organizations that need to comply with specific industry regulations (like banking or healthcare), the billing system provides additional compliance features: detailed audit trails, role-based access to billing information, and integration with enterprise security systems. These features enable organizations to meet their regulatory obligations while using CodingAgent.",
        "Payment data is encrypted using industry-standard encryption (AES-256 for data at rest, TLS 1.3 for data in transit). The system undergoes regular security audits and penetration testing to identify and address potential vulnerabilities. This comprehensive security approach ensures that payment information is protected against both external attacks and internal threats."
      ]
    }
  ],
  "faq": [
    {
      "question": "What payment methods are accepted?",
      "answer": "CodingAgent accepts UPI (through Google Pay, PhonePe, Paytm, and other UPI apps), NetBanking (all major Indian banks), and credit/debit cards. All payments are processed in INR with no international markups."
    },
    {
      "question": "Are prices inclusive of GST?",
      "answer": "Yes, all published prices are inclusive of GST. The GST amount is calculated automatically based on your location and GSTIN, and is shown separately on invoices for transparency."
    },
    {
      "question": "Can I get a custom invoice format?",
      "answer": "Yes, enterprise customers can request custom invoice templates with additional fields, company branding, or specific formats required by their accounting systems."
    },
    {
      "question": "How does token-based pricing work?",
      "answer": "You pay for the tokens (words/pieces of code) sent to and generated by AI models. Local models running on your hardware have no token cost. Cloud models have per-token costs that vary by model. You can set budgets and receive alerts when approaching limits."
    },
    {
      "question": "Is there a free tier?",
      "answer": "Yes, CodingAgent offers a free tier with limited token usage per month. This enables developers to try the platform and understand the value before committing to a paid plan. The free tier includes access to local models with no token limits."
    }
  ],
  "sources": [
    {
      "label": "CodingAgent source repository",
      "href": "https://github.com/CodesbyFebin/Coding-Agent"
    }
  ]
};
